### ISSUE TITLE
useErrorBoundary no longer takes an error as argument

### ISSUE THREAD

**Issue by Volcomix** [bvaughn/react-error-boundary#132]
Hi and thank you for this awesome project!

I'm currently relying on `useErrorHandler(error)` to show my error fallback in a side panel inside the app, when `error` comes from a parent component of the error boundary. I can describe my use case more in depth if needed because that might be a contrived usage of the error boundary.

After migrating to `react-error-boundary` 4.0.0, the new hook `useErrorBoundary` no longer takes an error as argument and I am wondering:
* what is the reasoning behind this change?
* how should we now show the error boundary when the error object comes as a result of a hook or as a property of the component?

Depending on the replies, I could help to update the readme to describe the recommended way of using the library in such use case.

Thanks!

**Comment by bvaughn** [comment]
This change was intentional. The hook now returns two methods:
* One to show the nearest error boundary. (Typically this one would be called from an event handler or during an async effect.)
* One to dismiss the nearest visible error boundary.

I wasn't involved in (or really even aware of) the previous `useErrorHandler` hook, but its API didn't make sense to me for a few reasons:
* All it did was `throw` the provided value. If a component already has a reference to the error, it can just `throw` itself.
* It didn't support `null` or `undefined` throwable values, which– although an edge case– is something that can happen in JavaScript.

> how should we now show the error boundary when the error object comes as a result of a hook or as a property of the component?

The easiest way would be to just _throw the value_ directly.
### Before
```js
function Greeting() {
  const [name, setName] = React.useState('')
  const {greeting, error} = useGreeting(name)
  useErrorHandler(error)
```
### After
```js
function Greeting() {
  const [name, setName] = React.useState('')
  const {greeting, error} = useGreeting(name)
  if (error) {
    throw error;
  }
```

**Comment by Volcomix** [comment]
Thank you for the very detailed answer. Everything makes perfect sense. I also like how throwing directly from the render function is decoupled from the library and would just work with any kind of error boundary.

Given how well structured is your reply, do you think it could make sense to link this issue in the [release note](https://github.com/bvaughn/react-error-boundary/releases/tag/4.0.0) to help during the migration?

**Comment by bvaughn** [comment]
Yup. Good call!

Here's an example I put together for using the hook to reset the boudnary state, too:
https://codesandbox.io/s/nostalgic-browser-e9lpmf
