### ISSUE TITLE
Getting children of ErrorBoundary in render functions

### ISSUE THREAD

**Issue by tbowmo** [bvaughn/react-error-boundary#176]
- `react-error-boundary` version: 4.0.12

Problem description:

Not a bug per se, but I need to have access to the original children in the ErrorBoundary when rendering my fallback component, as we might just show a toast, and then the original content.

Suggested solution:
Add children to the props/parameters to the fallbacks

**Comment by bvaughn** [comment]
Sorry but this isn’t something I can support.

Re-rendering the original children would cause the same error that triggered the boundary to be thrown again, on loop.

What you would need to do would be to render with the previous props/state, but the error boundary can’t do that- since the props/state change that threw could occur anywhere deep inside of the tree.
