### ISSUE TITLE
How to know if ReactErrorBoundary has succeed and finished because i want to do something then ? 

### ISSUE THREAD

**Issue by sandysameh** [bvaughn/react-error-boundary#197]
and if i set my starte as 
hasNoError = false 

onError=()=>{
hasNoError = true
}
and a useEffect {
if(!hasNoError){
//then my logic
},[hasNoError]
}
then it runs on the first time and does my success logic even tho i want it to be after 100% sure i have succedded ?

**Comment by bvaughn** [comment]
You wouldn’t want to use a variable like that. Better to use a ref value for has-error. But I’m not really sure I understand the question.

**Comment by sandysameh** [comment]
Ok let me simplify want i need. 
So for my case i care about the crash number because depending on each crash i have a different fallback. 

so on the first crash i want to preview 
a` reload page button ` and on click of this i add the crash number in LS 
on second crash i want a ` clear relevant LS error `and on click of this i add the crash number in LS 
and on third crash or more we have a text **contact Customer support**. 

So inorder for me to presist the crash number i had to save the crash count in LS. 
but i am not sure how do i know that the  ReactErrorBoundary didn't through errors and not just because it's an inital render to remove the crash number from LS or make it reset to 0. 

that is why i don't like the useEffect approach and i am not sure how we can implement this.

**Comment by bvaughn** [comment]
> that is why i don't like the useEffect approach and i am not sure how we can implement this.

I think you should probably just write your own error boundary. It's [really easy](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) to write one. This library isn't doing _all that much_, and as a result I don't think it's worth even trying to support less common use cases in it (because it would add more complexity than is warranted).

If you want to track the number of times an error boundary has been shown, you could store that counter in React state or context, but again– I think you might just be better off writing your own custom error boundary logic for this.
