### ISSUE TITLE
Expose a decorator function for Redux containers.

### ISSUE THREAD

**Issue by hally9k** [bvaughn/react-error-boundary#4]
I propose exposing an additional function that returns the given component wrapped with the error boundary component. Much like `connect()` from the `react-redux` api.

When exposing the class alone, it lends it's self to wrapping a component in JSX which isn't a good fit in some scenarios. For example if a Redux container is referenced in a React Router route as a component reference there is no nice place to use this lib.

With a function as described we could do the following in our redux continers:

```
export default connect(mapStateToProps, mapDispatchToProps)(
   withErrorBoundary(Component, FallbackComponent, errorHandler)
)
```

**Comment by bvaughn** [comment]
Just released via 1.1.0

Thanks!

**Comment by blling** [comment]
If i want to `dispatch` an action in `ErrorHandler`, how to get the redux `dispatch`?  I use `this` as follows but the `this.props` is undefined. 
```javascript
export default compose(
  withReducer,
  withSaga,
  (component) => withErrorBoundary(component
    , ErrorFallback
    , (error) => this.props.dispatch(handleError(error))
  ), // use ErrorBoundary
  withConnect,
)(HomePage);
```

**Comment by bvaughn** [comment]
I think there might be some confusion about how [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) work. They specifically preserve the lexical `this` when and where They are declared, rather than when they're invoked. For example:

```js
class ExampleClass {
  callMethods() {
    arrowFunction();            // 'this' will be the window object
    regularFunction();          // 'this' will be the window object
    arrowFunction.call(this);   // 'this' will be the window object
    regularFunction.call(this); // 'this' will be the instance of ExampleClass
  }
}

const arrowFunction = () => {
  console.log('arrowFunction', this);
};

function regularFunction() {
  console.log('regularFunction', this);
}

new ExampleClass().callMethods();
```

Regardless of the type of method you pass in though, [the `onError` callback is invoked as a standalone function](https://github.com/bvaughn/react-error-boundary/blob/0edfc1c126a52c9493bf0e5fc6b84497a5e19a7f/src/ErrorBoundary.js#L38) inside of `react-error-boundary` so it won't have a `this`.

I guess I could change the code to preserve the `this`, but in that case I think you'd still need to use `this.props.children.props.dispatch` to get at the `dispatch` property.

**Comment by bvaughn** [comment]
Just published 1.2.0 with support for `this` but you'll need to switch away from arrow function to a regular function if you want to use it.

**Comment by blling** [comment]
Wow, so fast, i will try it tomorrow, thanks very much @bvaughn !
If i do not use `this`  is there another good practice?

**Comment by bvaughn** [comment]
You are welcome.

I haven't used Redux in a long time. I'm not sure what the best way to approach this is to be honest.

**Comment by blling** [comment]
Get it, thanks for your great work again. ^_^
