### ISSUE TITLE
Bug: onResetKeys only triggers reset after second render

### ISSUE THREAD

**Issue by 0xR** [bvaughn/react-error-boundary#74]
- `react-error-boundary` version: 3.0.2
- `node` version:14
- `npm` version:6.14

Relevant code or config
It seems to occur because of the `return` statement here:
https://github.com/bvaughn/react-error-boundary/blob/f0c22663c5fd8f9dd22907aa8953eb9dd0bcf7d8/src/index.js#L38-L41

What you did:
```
export const ErrorBoundary = ({ children }) => {
  const location = useLocation();
  return (
    <ReactErrorBoundary
      FallbackComponent={FallbackComponent}
      resetKeys={[location]}
    >
      {children}
    </ReactErrorBoundary>
  );
};
```

What happened:
I have to click the "no error" link twice before the error boundary resets.
This only occurs the first time when I load the page. After that there is issue.

Here you can see I have to click twice on "no error" after the refresh. The url changes on the first click, the errorboundary resets on the 2nd click.
![errorboundary-bug-2020-10-19_13 46 27](https://user-images.githubusercontent.com/6420016/96447321-02c35880-1212-11eb-8cc2-46e727207e77.gif)

Reproduction repository:
https://github.com/0xR/errorboundary

For some reason there is no issue on codesandbox:
https://codesandbox.io/s/hungry-mountain-lvggg?file=/src/App.js

Problem description:

Suggested solution:
Remove the `return` statement: https://github.com/bvaughn/react-error-boundary/blob/f0c22663c5fd8f9dd22907aa8953eb9dd0bcf7d8/src/index.js#L40

**Comment by kentcdodds** [comment]
Hey @0xR,

Thanks for the demo and suggestion. I'm not 100% I agree that this is the right approach, but if you'd like to open a pull request that included any necessary changes to tests along with your suggested fix I'd consider merging it. Thanks!

**Comment by jeysal** [comment]
Also ran into this. We're using `resetKeys={[pathname, query]}` (with I think makes more sense because it ignores hash changes), same problem. I've already made a repro before noticing there was already an issue for this, might as well throw that in here as well (it reproduces with `yarn && yarn test`): https://github.com/jeysal/error-boundary-resetkeys-repro
Note that `react-error-boundary@2` passes, so I also strongly believe this is the update handling added in #68.
